logging:
    file: /home/huoshan/log/timesheet.log
    level.root: DEBUG

server:
    port: 9000
 
spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/timesheet?characterEncoding=utf-8
        username: root
        password: llhua123
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: select 1
        continue-on-error: false
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
    jpa:
        properties.hibernate.hbm2ddl.auto: update
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
   
    
